### ISSUE TITLE
Unable to use the parser

### ISSUE THREAD

**Issue by JoaoSobral** [alfonsrv/mail-parser-reply#3]
I have a function where I am calling your library. By simple copying your example (even using the "foobar" as data) I am getting the following error:
`    mail_message = EmailReplyParser.read(text=mail_body, languages=languages)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: EmailReplyParser.read() got an unexpected keyword argument 'languages'`

Function
`def beautify_body(body):
 
    # Remove HTML code
    soup = BeautifulSoup(body, 'html.parser')
    body = soup.get_text()
   
    mail_body = 'foobar'; languages = ['en', 'de']
    mail_message = EmailReplyParser.read(text=mail_body, languages=languages)
    print(mail_message.replies)

    return body`

**Comment by alfonsrv** [comment]
Thanks for the heads up – the documentation had a small error.

Usage is as follows:

```
_ = EmailReplyParser(
        languages=languages
    ).read(
        text=_text_html or _text_plain
    )
```
