### ISSUE TITLE
Question - why some test cases are commented?

### ISSUE THREAD

**Issue by IzioDev** [alfonsrv/mail-parser-reply#4]
Hi,

First of all, thank you for the great work you did on this package.

I'm coming from the node world, and after spending some time on looking for 'the-best-solution' (free & open-source) to parse email, with their contents (replies), i found this one, and I think this offers great extensibility.

I was looking at the code, pretty-clean ! Wondering why some test cases are commented tho?

Thanks in advance.

**Comment by alfonsrv** [comment]
Thanks for the heads-up. Likely a leftover and oversight from when I initially implemented the package, doing some testing.

I cleaned up the code, so it should be fine now. Hope the package still satisfies your needs since May~
